import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";
import NextAuthProvider from "@/provider/NextAuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <NextAuthProvider>
    <html lang="en" >
   
       <body
    suppressHydrationWarning
    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
  >
        
        <Navbar></Navbar>
       <div className="min-h-screen  pt-20">
          {children}
       </div>
        <Footer></Footer>
        
      </body>
      
    </html>
    </NextAuthProvider> 
    
  );
}
